In [1]:
import pandas as pd
import numpy as np
from scipy.linalg import eig

def calculate_ahp_weights(data, ppt_criteria, criteria_pairs, response_scale):
    """
    Calculate AHP weights using a pairwise comparison matrix.

    Parameters:
        data (pd.DataFrame): The survey data containing responses.
        ppt_criteria (list): List of criteria, e.g., ["People", "Process", "Technology"].
        criteria_pairs (list): List of string pair comparisons, e.g., ["3. A: People. B: Process"].
        response_scale (dict): Mapping of response text to numeric scale for AHP.

    Returns:
        tuple: The pairwise comparison matrix and the priority vector (weights).
    """
    n_criteria = len(ppt_criteria)  # Number of criteria
    matrix = np.ones((n_criteria, n_criteria))  # Initialize matrix with 1s

    # Fill the matrix using the criteria_pairs and response_scale
    for i, pair in enumerate(criteria_pairs):
        response = data.iloc[0].get(pair, None)  # Retrieve response for the pair
        if response is not None:
            value = response_scale.get(response, 1)  # Use response scale or default to 1
            # Determine matrix indices based on pair index
            if i == 0:
                matrix[0, 1] = value
                matrix[1, 0] = 1 / value
            elif i == 1:
                matrix[0, 2] = value
                matrix[2, 0] = 1 / value
            elif i == 2:
                matrix[1, 2] = value
                matrix[2, 1] = 1 / value

    # Compute eigenvector-based priority weights
    eigenvalues, eigenvectors = eig(matrix)
    max_index = np.argmax(eigenvalues)  # Find index of the largest eigenvalue
    priority_vector = np.real(eigenvectors[:, max_index]).astype(float)
    priority_vector /= priority_vector.sum()  # Normalize priority vector

    return matrix, priority_vector


## Define response scale and data

In [2]:
# Define the survey response scale
response_scale = {
    "A mutlak lebih penting dibandingkan B": 9,
    "A sangat lebih penting dibandingkan B": 7,
    "A cukup lebih penting dibandingkan B": 5,
    "A sedikit lebih penting dibandingkan B": 3,
    "Sama pentingnya": 1,
    "B sedikit lebih penting dibandingkan A": 1/3,
    "B cukup lebih penting dibandingkan A": 1/5,
    "B sangat lebih penting dibandingkan A": 1/7,
    "B mutlak lebih penting dibandingkan A": 1/9
}

# Load your survey data from CSV
data = pd.read_csv("~/Downloads/export-core_banking_system_csf_survey-2024-11-18-07-48-33.csv")


## PPT Priority Vector Matrix

In [3]:
# Define criteria and criteria pairs
ppt_criteria = ["People", "Process", "Technology"]
ppt_criteria_pairs = [
    "3. A: People. B: Process",
    "4. A: People. B: Technology",
    "5. A: Process. B: Technology"
]

# Call the function
ppt_matrix, ppt_priority_vector = calculate_ahp_weights(data, ppt_criteria, ppt_criteria_pairs, response_scale)

print("Pairwise Comparison Matrix:\n", ppt_matrix)
print()
print("Priority Vector (AHP Weights):")
for criterion, weight in zip(ppt_criteria, ppt_priority_vector):
    print(f"{criterion}: {weight:.4f}")


Pairwise Comparison Matrix:
 [[1.         7.         5.        ]
 [0.14285714 1.         3.        ]
 [0.2        0.33333333 1.        ]]

Priority Vector (AHP Weights):
People: 0.7383
Process: 0.1702
Technology: 0.0915


## People Priority Vector

In [4]:
people_criteria = [
    "Dukungan manajemen senior",
    "Alokasi sumber daya",
    "Kompatibilitas Teknologi",
    "Perubahan manajemen dan Adaptasi User"
]

people_criteria_pairs = [
    f"7. A: {people_criteria[0]}. B: {people_criteria[1]}",
    f"8. A: {people_criteria[0]}. B: {people_criteria[2]}",
    f"9. A: {people_criteria[0]}. B: {people_criteria[3]}",
    f"10. A: {people_criteria[1]}. B: {people_criteria[2]}",
    f"11. A: {people_criteria[1]}. B: {people_criteria[3]}",
    f"12. A: {people_criteria[2]}. B: {people_criteria[3]}"
]

# Call the function
people_matrix, people_priority_vector = calculate_ahp_weights(data, people_criteria, people_criteria_pairs, response_scale)

print("Pairwise Comparison Matrix:\n", people_matrix)
print()
print("Priority Vector (AHP Weights):")
for criterion, weight in zip(people_criteria, people_priority_vector):
    print(f"{criterion}: {weight:.4f}")

Pairwise Comparison Matrix:
 [[1.  5.  5.  1. ]
 [0.2 1.  1.  1. ]
 [0.2 1.  1.  1. ]
 [1.  1.  1.  1. ]]

Priority Vector (AHP Weights):
Dukungan manajemen senior: 0.4890
Alokasi sumber daya: 0.1403
Kompatibilitas Teknologi: 0.1403
Perubahan manajemen dan Adaptasi User: 0.2304


## Process Priority Vector

In [5]:
# Define process-related criteria
process_criteria = [
    "Rekayasa ulang proses bisnis",
    "Kebutuhan sistem yang jelas",
    "Standar operasional yang jelas",
    "Mitigasi dan manajemen risiko"
]

# Define process-related criteria pairs
process_criteria_pairs = [
    f"14. A: {process_criteria[0]}. B: {process_criteria[1]}",
    f"15. A: {process_criteria[0]}. B: {process_criteria[2]}",
    f"16. A: {process_criteria[0]}. B: {process_criteria[3]}",
    f"17. A: {process_criteria[1]}. B: {process_criteria[2]}",
    f"18. A: {process_criteria[1]}. B: {process_criteria[3]}",
    f"19. A: {process_criteria[2]}. B: {process_criteria[3]}"
]

# Call the function
process_matrix, process_priority_vector = calculate_ahp_weights(
    data, process_criteria, process_criteria_pairs, response_scale
)

# Print Pairwise Comparison Matrix
print("Process Pairwise Comparison Matrix:\n", process_matrix)

# Print Priority Vector with process-related criteria names
print("Process Priority Vector (AHP Weights):")
for criterion, weight in zip(process_criteria, process_priority_vector):
    print(f"{criterion}: {weight:.4f}")


Process Pairwise Comparison Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Process Priority Vector (AHP Weights):
Rekayasa ulang proses bisnis: 0.2500
Kebutuhan sistem yang jelas: 0.2500
Standar operasional yang jelas: 0.2500
Mitigasi dan manajemen risiko: 0.2500


## Technology Priority Matrix

In [6]:
# Define technology-related criteria
technology_criteria = [
    "Keamanan yang kuat",
    "Skalabilitas infrastruktur IT",
    "Integrasi Sistem",
    "Performa dan kecepatan sistem"
]

# Define technology-related criteria pairs
technology_criteria_pairs = [
    f"21. A: {technology_criteria[0]}. B: {technology_criteria[1]}",
    f"22. A: {technology_criteria[0]}. B: {technology_criteria[2]}",
    f"23. A: {technology_criteria[0]}. B: {technology_criteria[3]}",
    f"24. A: {technology_criteria[1]}. B: {technology_criteria[2]}",
    f"25. A: {technology_criteria[1]}. B: {technology_criteria[3]}",
    f"26. A: {technology_criteria[2]}. B: {technology_criteria[3]}"
]

# Call the function
technology_matrix, technology_priority_vector = calculate_ahp_weights(
    data, technology_criteria, technology_criteria_pairs, response_scale
)

# Print Pairwise Comparison Matrix
print("Technology Pairwise Comparison Matrix:\n", technology_matrix)

# Print Priority Vector with technology-related criteria names
print("Technology Priority Vector (AHP Weights):")
for criterion, weight in zip(technology_criteria, technology_priority_vector):
    print(f"{criterion}: {weight:.4f}")


Technology Pairwise Comparison Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Technology Priority Vector (AHP Weights):
Keamanan yang kuat: 0.2500
Skalabilitas infrastruktur IT: 0.2500
Integrasi Sistem: 0.2500
Performa dan kecepatan sistem: 0.2500


In [7]:
def calculate_ci(matrix):
    """
    Calculate the Consistency Index (CI) for a given pairwise comparison matrix.

    Parameters:
        matrix (numpy.ndarray): Pairwise comparison matrix.

    Returns:
        float: The Consistency Index (CI).
    """
    eigenvalues, _ = eig(matrix)
    lambda_max = np.real(eigenvalues).max()  # Largest eigenvalue (real part)
    n = matrix.shape[0]  # Number of criteria (size of the matrix)
    ci = (lambda_max - n) / (n - 1) if n > 1 else 0  # Avoid division by zero
    return ci

# Calculate CI for criteria
technology_ci = calculate_ci(ppt_matrix)
print(f"PPT Consistency Index (CI): {technology_ci:.4f}")

# Calculate CI for people-related criteria
process_ci = calculate_ci(people_matrix)
print(f"People Consistency Index (CI): {process_ci:.4f}")

# Calculate CI for process-related criteria
process_ci = calculate_ci(process_matrix)
print(f"Process Consistency Index (CI): {process_ci:.4f}")

# Calculate CI for technology-related criteria
technology_ci = calculate_ci(technology_matrix)
print(f"Technology Consistency Index (CI): {technology_ci:.4f}")


PPT Consistency Index (CI): 0.1166
People Consistency Index (CI): 0.1133
Process Consistency Index (CI): -0.0000
Technology Consistency Index (CI): -0.0000


In [8]:
def calculate_ci_and_cr(matrix, ri_table):
    """
    Calculate the Consistency Index (CI) and Consistency Ratio (CR) for a given pairwise comparison matrix.

    Parameters:
        matrix (numpy.ndarray): Pairwise comparison matrix.
        ri_table (dict): Random Index table.

    Returns:
        tuple: (CI, CR)
    """
    eigenvalues, _ = eig(matrix)
    lambda_max = np.real(eigenvalues).max()  # Largest eigenvalue
    n = matrix.shape[0]  # Matrix size
    ci = (lambda_max - n) / (n - 1) if n > 1 else 0  # Consistency Index
    ri = ri_table.get(n, 0)  # Random Index based on matrix size
    cr = ci / ri if ri > 0 else 0  # Consistency Ratio
    return ci, cr

# Random Index table
ri_table = {
    1: 0.00, 2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12,
    6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49
}

# Calculate CI and CR for each criteria group
ppt_ci, ppt_cr = calculate_ci_and_cr(ppt_matrix, ri_table)
people_ci, people_cr = calculate_ci_and_cr(people_matrix, ri_table)
process_ci, process_cr = calculate_ci_and_cr(process_matrix, ri_table)
technology_ci, technology_cr = calculate_ci_and_cr(technology_matrix, ri_table)

# Print results
print(f"PPT CI: {ppt_ci:.4f}, CR: {ppt_cr:.4f}")
print(f"People CI: {people_ci:.4f}, CR: {people_cr:.4f}")
print(f"Process CI: {process_ci:.4f}, CR: {process_cr:.4f}")
print(f"Technology CI: {technology_ci:.4f}, CR: {technology_cr:.4f}")


PPT CI: 0.1166, CR: 0.2011
People CI: 0.1133, CR: 0.1259
Process CI: -0.0000, CR: -0.0000
Technology CI: -0.0000, CR: -0.0000
